# Generated by Django 3.2.12 on 2022-04-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_prompt_article_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='engine',
            field=models.CharField(choices=[('text-davinci-002', 'New Instruct Davinci'), ('text-davinci-001', 'Old Instruct Davinci'), ('text-curie-001', 'Instruct Curie')], max_length=150),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('nl', 'Dutch'), ('fr', 'French')], max_length=150),
        ),
    ]
