# Generated by Django 3.2.12 on 2022-04-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_prompt_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='article_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
