# Generated by Django 3.2.12 on 2022-04-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_alter_prompt_article_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='article',
            new_name='prompt',
        ),
    ]
