# Generated by Django 3.2.12 on 2022-04-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_rename_article_prompt_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='audio',
            field=models.FileField(null=True, upload_to='audios/'),
        ),
    ]
