# Generated by Django 3.2.12 on 2022-04-20 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_prompt_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('stars', models.CharField(blank=True, choices=[('1Star', 'Poor'), ('2Stars', 'Below Average'), ('3Stars', 'Average'), ('4Stars', 'Above Average'), ('5Stars', 'Excellent')], max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.prompt')),
            ],
        ),
    ]
