# Generated by Django 3.2.12 on 2022-04-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='comments',
        ),
    ]
