# Generated by Django 3.2.12 on 2022-04-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_rename_body_review_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='VOTE_RATIO',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='VOTE_TOTAL',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
