# Generated by Django 3.2.12 on 2022-04-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_auto_20220420_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='rate',
        ),
    ]
