# Generated by Django 3.2.12 on 2022-04-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_rename_stars_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(blank=True, choices=[('None', None), ('1Star', 'Poor'), ('2Stars', 'Below Average'), ('3Stars', 'Average'), ('4Stars', 'Above Average'), ('5Stars', 'Excellent')], max_length=100, null=True),
        ),
    ]
