# Generated by Django 3.2.12 on 2022-04-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0012_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(blank=True, choices=[('None', None), ('1', 'Poor'), ('2', 'Below Average'), ('3', 'Average'), ('4', 'Above Average'), ('5', 'Excellent')], max_length=100, null=True),
        ),
    ]
