# Generated by Django 3.2.12 on 2022-04-26 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0013_alter_review_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptReview',
            fields=[
                ('article_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('prompt', models.TextField()),
                ('engine', models.CharField(choices=[('text-davinci-002', 'New Instruct Davinci'), ('text-davinci-001', 'Old Instruct Davinci'), ('text-curie-001', 'Instruct Curie')], max_length=150)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('nl', 'Dutch'), ('fr', 'French')], max_length=150)),
                ('summary', models.TextField(null=True)),
                ('audio', models.FileField(null=True, upload_to='audios/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, choices=[('None', None), ('1', 'Poor'), ('2', 'Below Average'), ('3', 'Average'), ('4', 'Above Average'), ('5', 'Excellent')], max_length=100, null=True)),
                ('VOTE_TOTAL', models.IntegerField(blank=True, default=0, null=True)),
                ('VOTE_RATIO', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='prompt',
            name='myRange',
            field=models.IntegerField(blank=True, default=400, null=True),
        ),
    ]
