# Generated by Django 3.2.12 on 2022-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0014_auto_20220426_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='myRange',
            field=models.CharField(default=400, max_length=10),
        ),
    ]
