# Generated by Django 3.2.12 on 2022-04-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0015_alter_prompt_myrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='myRange',
            field=models.CharField(default=400, max_length=4),
        ),
    ]
