# Generated by Django 3.2.12 on 2022-04-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0016_alter_prompt_myrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptreview',
            name='myFile',
            field=models.FileField(blank=True, null=True, upload_to='Docs/'),
        ),
    ]
