# Generated by Django 3.2.12 on 2022-04-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0017_promptreview_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='myFile',
            field=models.FileField(blank=True, null=True, upload_to='Docs/'),
        ),
    ]
