# Generated by Django 3.2.12 on 2022-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0018_prompt_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='promptreview',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
