# Generated by Django 3.2.12 on 2022-05-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0019_auto_20220428_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptreview',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
